- .github/workflows/python_ci.yml
- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
1. Unit tests added for all methods except for signal, which is incomplete and will be done in a different PR. All external calls are mocked out.
2. Slight correction to tests directory since the file wasn't in the right subdir.
3. Use the .pylintrc that was already present and remove redundant disables.
4. Rename github action to include "python"
Other notes
- Linting is disabled on test directory for now, but don't feel super strongly so open to debate. 
- Also side note is that the CI right now runs in ~30-1min with no multiplier, just to keep in mind for [billing](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions). We get a few thousand runs a month so I imagine it'll be fine for a while, but …
> Add unit tests for remaining functions except `signal`

- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
1. Add some happy path tests to Signal. There's probably a few more cases worth testing, but for now it's better than nothing.
2. Refactor some single -> double quotes, variable names, and docstrings
> Happy path unit tests for `signal`

- R-packages/covidcast/R/covidcast.R
I fixed a small big in summarizing the metadata.
> Correlation utils: fix bug in meta summary

- Python-packages/covidcast-py/setup.py
Forgot to do this when i unzipped the files
> fix shapefile path in setup.py

- R-packages/covidcast/R/covidcast.R
Important for automation that fetches lots of data.
> Make missing data warning say what signal/source is missing

- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/R/plot.R
- R-packages/covidcast/man/plot.covidcast_signal.Rd
- R-packages/covidcast/vignettes/correlation-utils.Rmd
- R-packages/covidcast/vignettes/plotting-signals.Rmd
Hi all, particularly @capnrefsmmat @chinandrew, some miscellaneous plotting fixes in response to comments raised by Andrew in #43.
I actually made the commit messages a bit more informative here, so hopefully you can tell what's going on.  This PR should address #73 but unfortunately not #76.  The latter appears to be a bug with `usmap::usmap_transform()`.  I'll write more on that issue.
Alex: I decided to number the vignette entries already, because I made a couple small edits to the vignettes anyway (and I know the correlations one takes a long time to rebuild).  And this will incentivize us (me) to write a third vignette sooner than later, so it doesn't look so barebones with just two, for too long.
> Plotting fixes

- Python-packages/covidcast-py/covidcast/plotting.py
- Python-packages/covidcast-py/docs/changelog.rst
- Python-packages/covidcast-py/docs/conf.py
- Python-packages/covidcast-py/docs/plot_examples.rst
- Python-packages/covidcast-py/docs/plotting.rst
- Python-packages/covidcast-py/setup.py
Closes #90 
- increments version to 0.1.0 in setup.py and conf.py
- updates changelog
- various documentation changes
> Update Python documentation before next release 

- R-notebooks/fb_dashboard.Rmd
For the Facebook survey dashboard.
> Set nicer date labels on the time series graphs

- R-packages/covidcast/DESCRIPTION
- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/R/data.R
- R-packages/covidcast/man/county_census.Rd
- R-packages/covidcast/man/county_geo.Rd
- R-packages/covidcast/man/covidcast_signal.Rd
- R-packages/covidcast/man/msa_census.Rd
- R-packages/covidcast/man/state_census.Rd
- R-packages/covidcast/man/state_geo.Rd
A few small doc updates. 
@JedGrabman You can commit your doc updates for data.R to this PR, [as Alex pointed out is needed](https://github.com/cmu-delphi/covidcast/pull/122#issuecomment-713019702).
@capnrefsmmat Look for my comment below about another doc update that's needed before merging.
> Doc update

- R-packages/evalcast/R/plot_calibration.R
Addresses R CMD check giving a NOTE: "plot_coverage: no visible binding for global variable ‘nominal_coverage_prob’"
> Add .data$ before nominal_coverage_prob

- R-notebooks/dashboard_functions.R
- R-notebooks/doctor_visits_dashboard.Rmd
- R-notebooks/ght_dashboard.Rmd
- R-notebooks/hospital_admissions_dashboard.Rmd
- R-notebooks/make.R
- R-notebooks/quidel_dashboard.Rmd
Per #32, this adds a basic coverage and sample size dashboard for a number of indicators, using our own API.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970301663177) by [Unito](https://www.unito.io/learn-more)
> Add Quidel, Doctor Visits, Hospital Admissions, GHT R dashboards to the example notebooks

- docs/talks/aws/talk.Rmd
> Fix footer

- R-packages/covidcast/R/covidcast.R
See Issue #251 for more details
> Don't warn when retrieving all geo_values, fix rlang error

- R-packages/evalcast/R/evaluate.R
- R-packages/evalcast/R/get_covidhub_predictions.R
Reverts cmu-delphi/covidcast#265
Needs more review.
> Revert "Add S3 class typing to cards"

- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/R/data.R
- R-packages/covidcast/R/wrangle.R
- R-packages/covidcast/index.md
- R-packages/covidcast/vignettes/correlation-utils.Rmd
- R-packages/covidcast/vignettes/multi-signals.Rmd
Improve cross-references and fix a couple typos.
> Minor R package documentation & typo fixes

- R-packages/evalcast/DESCRIPTION
- R-packages/evalcast/R/manage_cards.R
- R-packages/evalcast/R/plot_trajectory.R
- R-packages/evalcast/man/plot_trajectory.Rd
- R-packages/evalcast/man/print.prediction_card.Rd
- R-packages/evalcast/man/print.score_card.Rd
fix some of the `plot_trajectory()` problems in #332 .
> Evalcast hotfix

- R-packages/covidcast/DESCRIPTION
> Update covidcast DESCRIPTION

- R-notebooks/covidhub_evaluation.Rmd
Description:
Checks for previously saved data before requesting / processing new data, leading to substantial speed improvements for weekly updates.
Change log:
- Checks for previous `predictions_cards` and `score_cards` before requesting or processing data.
- Only save `predictions_cards` and `score_cards`, not all values.
- Updated code for determining which dates to request (includes only desired dates, doesn't use NA).
> Make covidhub_evaluation.Rmd more efficient when previous data exists

- R-notebooks/index.css
- R-notebooks/index.html
Add a wrapper for the individual dashboards to easily navigate between them.
- Adds an index.html
- Adds CSS
Incremental progress for #32
> Add html and CSS wrapper for dashboards

- .github/workflows/r_covidcast_ci.yml
Fixes #369 
Adds a usethis dependency to the R covidcast yaml.
> Add libgit2 dependency to CI

- Python-packages/covidcast-py/docs/changelog.rst
- Update some things that were missing from old release changelogs.
> Update Python changelog with missing details from past releases

- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/man/covidcast_signal.Rd
- R-packages/covidcast/man/covidcast_signals.Rd
> Support nation and HHS as geo_types in R client

- R-packages/covidcast/R/plot.R
> Make sf not print messages about CRS, shapefiles, etc.

- Python-packages/covidcast-py/covidcast/covidcast.py
Fixes #374 .
- Add hhs and nation to valid geo resolutions
> Support nation and HHS geo types in Python client

- R-packages/covidcast/R/covidcast.R
See #390.
I started thinking about how to test this, but it seems like it'll be awkward to do; suggestions welcome for a test that reuses some of the existing data files.
> Fix fetch warnings noted in #390

- R-packages/evalcast/R/download_signals.R
- R-packages/evalcast/R/plot_calibration.R
- R-packages/evalcast/vignettes/intro-evalcast.Rmd
Fix download_signals failures. Update wedge plots.
Fixes issues #399 , #404 .
> Wedge plots and download signals fix 

- .github/CODEOWNERS
cc @huisaddison 
This will require Addison's review on anything that touches modeltools; is there anyone else who should also be listed, or is this fine for now?
> List Addison as modeltools owner

- R-notebooks/dashboard_functions.R
- R-notebooks/dv_dashboard.Rmd
- R-notebooks/ght_dashboard.Rmd
- R-notebooks/hosp_dashboard.Rmd
- R-notebooks/jhu_dashboard.Rmd
- R-notebooks/quidel_dashboard.Rmd
- R-notebooks/safegraph_dashboard.Rmd
- R-notebooks/usa_facts_dashboard.Rmd
This refactors dashboard code to not have hardcoded 28-day dependence, allowing us to change the interval.
Continues work on #32
> Remove 28-day specific code from dashboard functions

- R-notebooks/chng_dashboard.Rmd
- R-notebooks/combo_cases_dashboard.Rmd
- R-notebooks/gs_dashboard.Rmd
- R-notebooks/hhs_hosp_dashboard.Rmd
This should expand the available dashboards to match the currently published set of data sources (not NMF but that's deprecated anyhow).
> Add dashboards for Change, Combo cases, Google Symptoms, HHS

- R-packages/evalcast/R/get_predictions.R
- R-packages/evalcast/man-roxygen/apply_corrections-template.R
- R-packages/evalcast/man/get_predictions.Rd
hopefully fixes @capolitsch 's bug at corrections time.
> remove ... from the corrections function.

- Python-packages/covidcast-py/Makefile
- Python-packages/covidcast-py/covidcast/covidcast.py
Bug fix where failing lints would pass CI, see https://github.com/cmu-delphi/covidcast-indicators/pull/753
Also fixed 2 minor lint erros
> Separate lint commands in make target

- R-packages/evalcast/vignettes/intro-evalcast.Rmd
Update function calls to reflect updates, change forecast dates to dec to deal with less NAs due to bigint problem in covidcast.  Fixes issue #449
> Fix intro vignette

- R-packages/modeltools/R/quantgen.R
- R-packages/modeltools/man/quantgen_forecaster.Rd
Minor fix to documentation in modeltools::quantgen_forecaster.
> Minor documentation changes to modeltools::quantgen_forecaster.

- R-packages/evalcast/R/plot_canonical.R
> Update plot_canonical to pass appropriate columns to scale_by_forecaster

- R-packages/modeltools/R/change.R
- R-packages/modeltools/R/deriv.R
- R-packages/modeltools/R/slide.R
- R-packages/modeltools/man/estimate_deriv.Rd
- R-packages/modeltools/man/pct_change.Rd
- R-packages/modeltools/man/slide_by_geo.Rd
Examples added for slide_by_geo(), pct_change() and estimate_deriv(). Users can get short code snippets from the help file instead of going to the vignettes.
> Add documentation examples.

- R-packages/covidcast/R/plot.R
Fixes issue #134, when all indicators are the same value.
> Adding minimum standard deviation

- R-packages/evalcast/R/get_covidhub_predictions.R
Retry forecaster file download if prior attempts fail, to ameliorate connection problems. Previously, when a single forecaster file failed to be downloaded, that whole forecaster would be missing from the dashboard data.
This change catches "cannot open URL" errors and retries the download up to 8 times, pausing in between to allow time for the connection to "recover".
- `get_covidhub_predictions.R` - add try-catch retry logic to the `download.file` command.
> Retry forecaster file download if prior attempts fail
