- .github/workflows/python_ci.yml
- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/requirements.txt
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
Summary of changes
1. Add type annotations to covidcast functions. 
2. Update CI to 3.6
Relatively low pri PR here, and open to discussing whether or not it's actually worth adding. I personally find type annotations helpful. Note that these annotations are not enforced at runtime by Python, and are purely for documentation and are often integrated into IDEs. I'm also running a type checker (mypy) on it as part of the CI, which can be slightly annoying and potentially not worth it - we can see how it goes and disable if needed.
A related discussion is if it's worth spending time standardizing some of the argument types to simplify code. I don't know enough about the end user, use case, likelihood of breaking existing user flows, and overall prioritization to make any judgments, but for …
> Python Type Annotations

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
Add columns to the end of the DF returned by `signal()` that have geo_type, data_source, and signal information. This will be used for downstream purposes.
See discussion in #25
> Add geo_type, data_source, and signal columns to the signal df

- Python-packages/covidcast-py/covidcast/covidcast.py
- R-packages/covidcast/R/covidcast.R
In preparation for higher traffic loads, point to the AWS read-only
replicas.
> Point both packages to the AWS API endpoint

- Python-packages/covidcast-py/covidcast/plotting.py
- Python-packages/covidcast-py/tests/covidcast/test_plotting.py
- Add a join_type argument to the `get_geo_df` function and the helper methods it uses.
The original implementation was that given a single day/signal/geo, the full GeoDF provided by the census would have the values joined in (so the output DF is the same dimensions). The problem is that someone can't choose append polgyons to their DF without this behaviour (e.g. they have 10 days of signals for a five specific counties and just want polygons inner joined to those), and if they have multiple values for the same geographies, the output starts being weird since it's no longer "Here's one row per region with it's respective value". Now, the user can just decide how they want the data joined. The original implementation is still default and will require a distinct series …
> 1. Add join_type to geoDF joining functions. 

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/covidcast/plotting.py
- Python-packages/covidcast-py/docs/changelog.rst
- Python-packages/covidcast-py/docs/plotting.rst
Some further improvement to the Sphinx docs before release.
@chinandrew, a couple questions for your review:
* I noticed that `plot_choropleth` had a type annotation saying it returned a `gpd.GeoDataFrame`, which is false, since we changed it to return the figure object. Is the type annotation checked by any of our tooling? I've never used Python type annotations, so I don't know how mypy fits in here.
* `plot_choropleth` pointed to the GeoSeries `plot` method, but I assume it actually uses the `GeoDataFrame` method, so I switched the links. Did I guess right?
> Further improve Python client docs

- Python-packages/covidcast-py/covidcast/plotting.py
- Python-packages/covidcast-py/tests/covidcast/test_plotting.py
Turns out 
```
data.loc[data.time_value == day_to_plot, :]
```
doesn't work because `day_to_plot` is a datetime.date object and the dataframe column is a pandas timestamp object, so instead we need to be doing this
```
data.loc[data.time_value == pd.to_datetime(day_to_plot), :]
```
Otherwise an empty dataframe gets returned and the function errors downstream. Added a basic test that just runs the function and will fail if it errors.
Guess it was a case that was never manually tested and we didn't have tests around plotting :(.
> Fix time_value bug on Python choropleth

- Python-packages/covidcast-py/covidcast/plotting.py
Fixes #75.
- Adjust colorbar size so it works on smaller plots and round decimals to 2 digits.
default size (12.8, 9.6)
(6,4)
> Change colorbar size and round decimals

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
Fixes #74 
Summary of changes
- Wrap the `geo_values` variable with `set()`, which deduplicates. 
- Add unit test for this behaviour. Also cleaned up them a bit.
> Deduplicate geo values for signal()

- .github/workflows/python_ci.yml
- Python-packages/covidcast-py/DEVELOP.md
- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/covidcast/geography.py
- Python-packages/covidcast-py/covidcast/plotting.py
- Python-packages/covidcast-py/requirements.txt
- Python-packages/covidcast-py/requirements_dev.txt
Closes #97 
- Add `pydocstyle` to lint docstrings
- Update developer readme with some more info. It's a bit bare still but better than nothing
- Add a requirements_dev.txt file with some packages that are needed for building the package and docs.
> Update README and add docstring style check

- Python-packages/covidcast-py/docs/getting_started.rst
- Python-packages/covidcast-py/docs/index.rst
- Python-packages/covidcast-py/docs/signals.rst
Addresses point 1 and 2 on #94
- Add section explaining the API
- Add an overview of sources and instructions on how to get the names to pass to covidcast.signal()
- Move installation info to "Getting Started"
I will say that the info duplication between this and the epidata api on sources (and the need to keep them in sync) is a bit messy, but probably ok for now. Also it probably looks better as a table, so I need to figure out how to get restructured tables to look good.
Once we finalize the language/structure, I can work on adding to the R docs as well.
> Add source overview to documentation

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/docs/changelog.rst
- Python-packages/covidcast-py/docs/getting_started.rst
- Python-packages/covidcast-py/docs/plot_examples.rst
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
- Remove the `direction` field, which has been null since August, from signal() output
- Update tests
- Remove corresponding documentation
- Add placeholder in changelog
> Python client: Remove `Direction` field from output and documentation

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/covidcast/errors.py
- Python-packages/covidcast-py/tests/covidcast/test_covidcast.py
Closes #139 
- Implement NoDataWarning custom warning for when no results are returned
- Change any other warnings to runtime warnings and raise them separately
- Add tests, and also fix two previous tests that weren't testing the right thing (oops)
> Add custom warning to be more informative when getting data

- R-packages/evalcast/R/err_measures.R
Ensure assert_that argument has length 1. 
Fail instead of succeed when a quantile is NA,
> Fix weighted_interval_score assert statement

- Python-packages/covidcast-py/Makefile
- Python-packages/covidcast-py/requirements_dev.txt
- Have dev requirements install before package dependencies. 
I can't reproduce this anymore, but one time I had a warning or error thrown when installing dependencies because wheel wasn't installed. Kinda weird but this should solve it.
> Reorder Python requirements in makefile

- .github/workflows/r_ci.yml
Closes #142
Summary of Changes:
* Add CI for R `covidcast` package (no evalcast yet)
Notes
* The check currently only fails if there are errors, and will not fail on warnings. There is currently one warning in the code.
* The CI config was pulled from the github actions premade template, which was mostly taken from the [r-lib](https://github.com/r-lib/actions/tree/master/examples#quickstart-ci-workflow) repo. I've changed it to not build vignettes, run on just one version of R, and on linux instead of mac (which is 10x cheaper).
* [RESOLVED by caching dependencies] It takes 6 minutes to install dependencies, which is quite a long time, and the check itself is <1min. I'm not sure if this can be optimized. That amount of time is a bit annoying to merge things fast and also drives up …
> Add CI for R package

- Python-packages/covidcast-py/covidcast/__init__.py
- Python-packages/covidcast-py/covidcast/geography.py
- Python-packages/covidcast-py/docs/signals.rst
- Python-packages/covidcast-py/tests/covidcast/test_geography.py
Closes #137 
* Add fips to abbr function and abbr to fips function, which requires doing basic string manipulation on the mapping file.
* update documentation
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970435180742) by [Unito](https://www.unito.io/learn-more)
> Add function for converting State Abbreviation to/from FIPS

- R-packages/covidcast/R/covidcast.R
Send multiple geo_values in comma delimited string
Request is returned as successful if any data retrieved, so treat day/geo_value combos with non-retreived data as warnings
Also, update error message to use human readable dates
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970431397793) by [Unito](https://www.unito.io/learn-more)
> Make use of new support for multiple geo_values in one request

- R-packages/evalcast/R/package.R
Fixes #218.  `download_signal()` and `get_covidhub_predictions()` are cached in memory.
> Memoize evalcast functions

- R-packages/evalcast/R/get_predictions.R
- R-packages/evalcast/tests/testthat/test-basic-functionality-runs-without-error.R
Adding more tests to the evalcast package (and fixing a bug involving geo_values).  The new tests:
- test that backfill buffer works
- test that additional arguments to forecaster works
- test that geo_values works
- test that start_day within signals works
I've verified that all tests pass and R CMD check runs with no errors, warnings, or notes.
> Evalcast tests

- R-packages/evalcast/R/plot_trajectory.R
One of arguments in `plot_trajectory()` had a trailing comma from a Chinese keyboard rather than the ASCII character.  This PR replaces it with the correct comma.
> Fix comma mismatch

- R-notebooks/make.R
Fix for #257. Tracks and propagates errors in generating dashboards into a non-zero exit code on the script.
> Propagate failures in dashboard generation so that a non-zero exit code is returned

- R-packages/evalcast/R/evaluate.R
- R-packages/evalcast/R/get_covidhub_predictions.R
Annotate an S3 class onto each tibble in the lists returned by `evalcast::get_covidhub_predictions()` and `evalcast::evaluate_predictions()` ("prediction_card" and "score_card", respectively). This will allow us to have generic methods for printing (#222) and aggregating (#221) the cards while allowing specialized behavior for the two types of cards.
See also #150.
> Add S3 class typing to cards

- R-packages/covidcast/DEVELOP.md
I propose we follow this process for future covidcast releases. This will require us to work on a branch until we're ready to release, but it affords us the opportunity to beta-test before release.
> Document a Git Flow release process

- .github/workflows/python_ci.yml
- .github/workflows/r_ci.yml
- R-packages/covidcast/tests/testthat/setup-options.R
- R-packages/covidcast/tests/testthat/teardown-options.R
Some changes happened to tests are failing on main. They're fixed on r-pkg-devel and this fixes on main.
> Update main to have same ci config as r-pkg-devel

- R-packages/evalcast/R/get_covidhub_predictions.R
- R-packages/evalcast/vignettes/intro_vignette.Rmd
For consistency with covidcast and with function name, have `get_forecast_dates` return a date object instead of a character object. I was unable to reproduce the issue originally described in #153 but the consistency fix should resolve the issue, since it appears that evalcast functions have built in flexibility and are able to handle either date or character objects.
> Dev date handle

- Python-packages/covidcast-py/setup.py
All the shapefiles are in subfolders, e.g. shapefiles/state/* or shapefiles/msa/*, so needed to add additional directory layer
> Fix Python client shapefile packaging

- R-packages/covidcast/R/covidcast.R
Fixes #317.
With this, you should be able to use `options(covidcast.base_url = "https://some-staging-server/...")` to have the package use a different endpoint.
> R custom API endpoint

- R-packages/evalcast/R/plot_trajectory.R
The functionality of `aggregate_cards()` was modeled after a subset of `plot_trajectory()`.  To avoid code reuse, we replace the duplicated code in `plot_trajectory()` with a call to `aggregate_cards()`.
This PR also fixes a bug in `plot_trajectory()` where the `forecast_date` column was unavailable and cleans up some readability issues.
> Migrate `plot_trajectory()` onto `aggregate_cards()`

- R-packages/covidcast/DESCRIPTION
- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/tests/testthat/test-covidcast.R
Bizarrely, even though `R CMD check` passed perfectly, the uses of dplyr and lubridate introduced in #275 didn't actually work in the installed package:
```
> library(covidcast)
> symptoms <- covidcast_signal("fb-survey", "smoothed_hh_cmnty_cli", geo_type="state")
Fetched day 2020-04-15 to 2020-06-23: 1, success, num_entries = 3601
Error in summarize(., geo_value = list(geo_value)) : 
could not find function "summarize"
> # and after fixing that:
> foo = covidcast_signal("fb-survey", "smoothed_hh_cmnty_cli", start_day="2020-11-20", end_day="2020-11-24", geo_type="state")
Fetched day 2020-11-20 to 2020-11-24: 1, success, num_entries = 153
Error in ymd(missing_time_values) : could not find function "ymd"
```
This is because there was no `@importFrom lubridate ymd` or equivalent, or the same …
> Fix imports from dplyr and lubridate

- R-packages/covidcast/tests/testthat/teardown-options.R
.defaultStringsAsFactors is a list with one named element,
$stringsAsFactors, so we pass the entire list to options() to set that
option back to its default.
My fault when I introduced this trick in #290. It was causing this error message after tests completed:
```
Error in options(stringsAsFactors = .defaultStringsAsFactors) : 
invalid value for 'stringsAsFactors'
```
> Fix error after R tests

- R-packages/covidcast/DESCRIPTION
- R-packages/covidcast/R/plot.R
- R-packages/covidcast/tests/testthat/test-plot.R
Fixes #270 
Summary of changes
- Update the metadata check in the plotting function to look specifically at mean and stdev values
- Add test that the warning is raised if one of the values is missing and not raised if both are present.
> Update R plotting metadata check

- R-packages/covidcast/tests/testthat/test-wrangle.R
Partially addresses #239
- add three tests:
a. test that you can lag a list of signals with a list of lags
b. test that you can lag a list of signals with a single lag vector applied to all elements
c. test that a full join occurs when aggregating two signals with different date ranges
> Add additional aggregation tests to R covidcast package

- R-packages/evalcast/R/err_measures.R
- R-packages/evalcast/R/evaluate.R
- R-packages/evalcast/tests/testthat/test-err-measures.R
Fixes a bug in `interval_coverage` (`which.min` was applied to a logical vector)
Change parameter to be coverage proportion instead of alpha = (1 - coverage)
Adds tests
Minor readability changes
> interval_coverage update

- .github/workflows/r_covidcast_ci.yml
- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/docs/changelog.rst
- Python-packages/covidcast-py/setup.py
- Python-packages/covidcast-py/tests/test_covidcast.py
See [this slack thread](https://delphi-org.slack.com/archives/C01E5M9KVN1/p1607616621001000).
Add a function that converts dates to timestamps and epiweek dates (CDC format, defined as length 6) to timestamps. Epiweeks are converted to the start of the epiweek using the `epiweeks` package.
Updated d ocs and changelog too, so I think we're good to rebuild docs and then release 0.1.2 after this is merged
> Add function to convert epiweeks to timestamps

- R-packages/evalcast/R/err_measures.R
- R-packages/evalcast/R/evaluate.R
- R-packages/evalcast/R/manage_cards.R
**Removes quantile information from scorecards**
Previously, scorecards contained a large quantity of duplicate information, since a row was created for each quantile. However, since overall error scores do not vary by quantile, the resulting tibbles had more rows than necessary, typically by a factor of 23.
This change removes `quantile` and `value` columns from scorecards, and fixes #400.
**Additional smaller changes:**
- Refactor `evaluate_predictions`
- Allow `weighted_interval_score` to process data that contains point estimates (i.e. `quantile = NA`, which does not affect the score)
- Remove requirement that dataframes passed to `collapse_cards` have a `geo_value` column
**Example with Covidcast data:**
```
forecaster = "CMU-TimeSeries"
forecast_dates = c("2020-09-21", "2020-09-28", …
```
> Remove quantile information from scorecards

- R-packages/covidcast/NEWS.md
- R-packages/covidcast/R/utils.R
- R-packages/covidcast/tests/testthat/test-geo_utils.R
This is to address #418.  The idea is to pass `grep_lookup()` a vector of the unique elements of the fips vector.
In the issue referenced above, I gave a small example that took over 30 seconds.  The same example is now about 20 times faster:
```
dat <- covidcast_signal(data_source = "safegraph", 
signal = "restaurants_visit_prop",
start_day = "2020-12-13", 
end_day = "2021-01-13",
geo_type = "county")
system.time({a <- fips_to_name(dat$geo_value)})
```
> Make fips_to_name faster.

- R-packages/modeltools/R/change.R
- R-packages/modeltools/R/deriv.R
- R-packages/modeltools/R/quantgen.R
- R-packages/modeltools/R/slide.R
- R-packages/modeltools/man/estimate_deriv.Rd
- R-packages/modeltools/man/pct_change.Rd
- R-packages/modeltools/man/quantgen_forecaster.Rd
- R-packages/modeltools/man/slide_by_geo.Rd
- docs/modeltoolsR/reference/estimate_deriv.html
- docs/modeltoolsR/reference/index.html
- docs/modeltoolsR/reference/pct_change.html
- docs/modeltoolsR/reference/quantgen_forecaster.html
- docs/modeltoolsR/reference/slide_by_geo.html
covidcast/modeltools -> covidcast/modeltoolsR in the roxygen in 4 functions. Required rebuilding roxygen and pkgdown.
> minor change to documentation due to broken link

- R-packages/evalcast/R/get_covidhub_predictions.R
Forecast date retrieval in evalcast broke, apparently because Github added a div to their HTML. This is a short-term fix to get the functionality working again, but issue #436 would be the long term solution.
> Fix date retrieval

- R-packages/evalcast/tests/testthat/test-evaluate.R
Fixes #452 by adding the correct geo type to the call to `evaluate_predictions()` rather than relying on the default.
> fix broken evaluate test

- R-packages/evalcast/R/get_predictions.R
- R-packages/evalcast/man/get_predictions.Rd
add a function to override the as_of date. Easily tested locally. The `get_predictions()` example fails (since there aren't historical as_of's in the API due to bigint) unless we override.
> add as_of_override

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/test_covidcast.py
Redundant after https://github.com/cmu-delphi/delphi-epidata/pull/237. Also removed a test that expected 2 calls with 2 geos.
> Remove individual geo calls

- Python-packages/covidcast-py/covidcast/covidcast.py
Fix
```
covidcast/covidcast.py:20:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
```
> Fix linting error that snuck into main

- R-packages/covidcast/R/wrangle.R
- R-packages/covidcast/tests/testthat/test-wrangle.R
Should fix issue #447. See there for details of the problem. 
* The solution is to simply set both `data_source` and `signal` inside the `x_all` object in `apply_shifts_one()`. Then do the `full_join()` on those columns as well. 
* There's also a test to ensure that this doesn't happen again.
* Note: there remains an `<NA>` in the issue column.
Finally, it may be worth considering that if `dt=NULL` and `format="long"`, we should maybe avoid all processing and just do `bind_rows()` on the list of signals.
> fix annoying NAs created by aggregate_signals()

- R-packages/evalcast/R/plot_canonical.R
- R-packages/evalcast/R/plot_coverage.R
- R-packages/evalcast/man/plot_coverage.Rd
Fixes #444 by changing `plot_coverage()` to take in predictions cards and joining it with downloaded covidcast data.
- `plot_coverage()` expects predictions cards rather than score cards
- `plot_coverage()` expects user-specified facet row and column variables rather than inferring them
- `plot_canonical()` has a fixed typo for error handling
- Fixes an error where `ggplot` wouldn't render the image because a numeric value hadn't been cast to a factor
> fix coverage plot issues

- R-packages/evalcast/R/scale_by_forecaster.R
In the R check, there are a few warnings that this avoids.
* But more importantly, for some reason, scaling seems to ignore any columns that come after the `base_forecaster` in the `df_list`. So we move it to the end. I don't understand why this is the case.
> scale_by_forecaster behavior

- R-packages/evalcast/R/plot_trajectory.R
- R-packages/evalcast/man/plot_trajectory.Rd
Updates `plot_trajectory` to have greater control of output plot (ability to define number of rows or columns, if output plot is produced).
> Allow selecting dimensions (nrow or ncol) in plot_trajectory

- R-packages/evalcast/R/get_covidhub_predictions.R
Fixing bugs due to unintuitive behavior of comparison functions between dates and character representations of dates. The comment sums up the rationale:
```
```
> Robustify date handling in get_covidhub_predictions

- R-packages/evalcast/R/get_covidhub_predictions.R
Bug fix. If `forecast_dates` is `NULL`, it is converted to an empty vector by the time the `is.null` check is reached.
> Handle empty date list in get_forecast_dates

- R-packages/evalcast/R/get_covidhub_predictions.R
- R-packages/evalcast/man/get_covidhub_forecaster_names.Rd
Allow filtering by designation when retrieving forecaster names
Reich Lab allows forecasts to be designated as [different types](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md#team_model_designation). Importantly, Reich Lab have stated that models not designated as "primary" will not be evaluated, so these designations are an indication of how forecasting groups expect their forecasts to be judged. This PR allows users to retrieve model names based on the designation.
> Allow filtering by designation when retrieving forecaster names

- R-packages/evalcast/R/get_covidhub_predictions.R
This fixes a typo that was breaking `get_covidhub_forecaster_names`
> Typo / bug fix for get_covidhub_forecaster_names

- R-packages/evalcast/R/get_predictions.R
- R-packages/evalcast/man-roxygen/signals-template.R
- R-packages/evalcast/man/baseline_forecaster.Rd
- R-packages/evalcast/man/get_predictions.Rd
- R-packages/evalcast/tests/testthat/test-predictions.R
Change the signature of `evalcast::get_predictions()` to allow for more flexibility of specifying data retrieval and to minimize the set of arguments passed to the forecaster.   Specifically:
- Remove `ahead` entirely from calls to `get_predictions()`
- Move `geo_type` from an explicit, separate argument to a column in `signals`
- Replace the `...` arguments with an explicit `forecaster_args` list of arguments
Since the calls to the forecasters no longer reflect some of the internal processing, additional tests have been added to verify that the right arguments are being passed to `download_signal()`
> Trim down arguments in `evalcast::get_predictions()`

- R-packages/modeltools/DESCRIPTION
- R-packages/modeltools/R/matrix.R
- R-packages/modeltools/man/create_train_and_predict_matrices.Rd
1. added dependency on `quantgen` to the DESCRIPTION.
2. rebuilt the docs to export @sgsmob 's  `create_train_and_predict_matrices()`
3. added `train_end_date` to the output of `create_train_and_predict_matrices()` (useful for cv).
> export the train/test matrix function

- R-packages/evalcast/R/error_measures.R
- R-packages/evalcast/tests/testthat/test-err-measures.R
Fixes a bug where WIS component scores could not be evaluated when a point estimate was present.
> Fix component scores when NAs present

- R-packages/evalcast/R/get_covidhub_predictions.R
Cleans up downloaded CSVs at the end of `get_forecaster_predictions_alt()` since files are not needed anymore.
> Clean up downloaded CSVs

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/test_covidcast.py
(This is a remake of PR #528; time travel is dangerous.)
This is the Python analogue of #380. Adds time_type support to `signal` and `_date_to_api_string` and modifies fetching logic slightly for both async and non-async calls.
A demo call to `nchs-mortality` with my local branch:
```
> remote_signal_name = "nchs-mortality"
> signal_type = "deaths_covid_incidence_num"
> geo_type = "state"
> start_day = date(2021, 1, 1)
> end_day = date(2021, 4, 20)
> df1 = covidcast.signal(remote_signal_name, signal_type, start_day, end_day, geo_type, time_type="week")
> df1 = df1.reset_index().set_index(["geo_value", "time_value"]).sort_index()
> print(df1.index.levels[1])
> print(df1["issue"].unique())
DatetimeIndex(['2020-12-27', '2021-01-03', '2021-01-10', '2021-01-17',
'2021-01-24', '2021-01-31', …
```
> Support weekly time_type in python package

- R-packages/covidcast/DESCRIPTION
- R-packages/covidcast/R/cor.R
- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/R/plot.R
- R-packages/covidcast/R/wrangle.R
- R-packages/covidcast/_pkgdown.yml
- R-packages/covidcast/inst/CITATION
- R-packages/covidcast/man/aggregate_signals.Rd
- R-packages/covidcast/man/as.covidcast_signal.Rd
- R-packages/covidcast/man/covidcast.Rd
- R-packages/covidcast/man/covidcast_cor.Rd
- R-packages/covidcast/man/covidcast_signal.Rd
- R-packages/covidcast/man/covidcast_signals.Rd
- R-packages/covidcast/man/plot.covidcast_signal.Rd
- R-packages/covidcast/man/print.covidcast_meta.Rd
- R-packages/covidcast/man/print.covidcast_signal.Rd
- R-packages/covidcast/man/summary.covidcast_meta.Rd
- R-packages/covidcast/man/summary.covidcast_signal.Rd
- R-packages/covidcast/vignettes/covidcast.Rmd
- R-packages/covidcast/vignettes/plotting-signals.Rmd
These are the changes I made both before our CRAN submission and during two rounds of review, leading to our [acceptance onto CRAN](https://cran.r-project.org/package=covidcast). (Yay!)
Mostly requesting review pro forma so you see what changed. Then I propose we rebuild all the docs, merge this into r-pkg-devel, and then merge r-pkg-devel to main so the docs update to describe the CRAN version and no longer recommend using devtools to install.
> Final CRAN modifications

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/tests/test_covidcast.py
The Flask API is returning `{'epidata': [], 'result': -2, 'message': 'no results'}` instead of `{'result': -2, 'message': 'no results'}`, so this check would pass half the time and lead to downstream problems. Open discussion on the flask/epidata side, but this might be a good robustification regardless.
> Update the condition for epidata in the response

- R-packages/evalcast/vignettes/intro-evalcast.Rmd
Vignette errored out at various points due to use of deprecated arguments and new arguments requited by various `evalcast` functions. This gets it working and shortens some output for a more readable output file.
> Update vignette; remove deprecated args

- R-packages/evalcast/R/get_target_response.R
Change `problem_dates` check from looking at length of `problem_dates`, which is always the same value and always equal to `forecast_dates`, to looking at the number of `TRUE`s in `problem_dates`. The old version of this check would always be true and always return an empty df if any `problem_dates` existed (if any dates requested from the API didn't return data), neglecting to return the data for the other requested dates.
In `get_target_response`,
- Return empty df when the number of `problem_dates` is the same as the number of forecast_dates.
- Subset `target_periods` to only those that had data returned from the API to match length of `out` and `forecast_dates`.
> Fix `problem_dates` check when fetching actual data from API

- Python-packages/covidcast-py/covidcast/covidcast.py
Fix failing linting by replacing `str.format()` with f-strings.
> Fix python covidcast test failures

- R-packages/evalcast/R/evaluate_predictions.R
Currently, truth data is joined on to `predictions_cards` in both `evaluate_covid_predictions`, before calling `evaluate_predictions`, and in `evaluate_predictions`. `evaluate_predictions` is passed separate `actual_data` and doesn't use the truth data contained in `predictions_cards`, so the first join is doing unnecessary work. Remove it, but enforce the same column ordering.
- Remove join in `evaluate_covid_predictions` that adds on truth data.
- Pass `grp_vars` to `evaluate_predictions`.
> Remove duplicate join in `evaluate_covid_predictions`

- R-packages/evalcast/R/evaluate_predictions.R
Reverts cmu-delphi/covidcast#563
Above change causes the forecast eval pipeline to fail with `Error: weighted_interval_score: quantiles must be unique.`. Reverting so we have a working pipeline for next week while I debug.
> Revert "Remove duplicate join in `evaluate_covid_predictions`"

- R-packages/evalcast/R/get_covidhub_predictions.R
Retry download regardless of error type to capture a variety of connection problems. Allow `try` to print all errors as they happen for logging purposes.
> Forecast eval support: make retries more general

- R-packages/evalcast/R/get_target_response.R
Retry truth data call from API if prior attempts fail to ameliorate connection problems. Same idea as #577 and followup #579.
- `get_target_response.R` - define a wrapper for `download_signal` that includes try-catch retry logic
> Retry truth data request from COVIDcast if prior attempts fail

- R-packages/modeltools/DESCRIPTION
[Quantgen](https://github.com/ryantibs/quantgen/tree/master/quantgen) recently reorganized its folder structure, which makes the installation
```
devtools::install_github("cmu-delphi/covidcast", ref="modeltools", subdir="R-packages/modeltools")
```
error out with a 404 when installing the quantgen dependency.
This PR should fix the ref. Tested locally by a manual git clone with
```
devtools::install("src/covidcast/R-packages/modeltools")
```
> Update quantgen dependency folder structure

- R-packages/evalcast/R/get_covidhub_predictions.R
This morning, the [forecast eval pipeline](https://github.com/cmu-delphi/forecast-eval/runs/7303389090?check_suite_focus=true) started getting
```
1. error in evaluating the argument 'x' in selecting a method for function 'as_date': error in evaluating the argument 'x' in selecting a method for function 'as_date': subscript out of bounds
```
for every forecaster requested. There have been no code changes on our end for the last several months, which implies a problem with one of the APIs or other non-package dependencies we use.
The errors are coming from [`lubridate` attempting to parse](https://github.com/cmu-delphi/covidcast/blob/60e5fdd72766b21a1ce6ee68ba5b7789f3bc6de7/R-packages/evalcast/R/get_covidhub_predictions.R#L434) dates from data filenames but there not being any dates to …
> Modify xpath to account for changed GH html on file lists

- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/R/plot.R
- R-packages/covidcast/R/wrangle.R
Which no longer uses .data (since that's really a data-masking thing)
> Fix for dev tidyselect

- R-packages/evalcast/R/get_covidhub_predictions.R
Same problem as in https://github.com/cmu-delphi/covidcast/pull/586. It looks like the highest and lowest-level elements are pretty stable, so just use those to find the filenames.
CC @brookslogan @dshemetov
> Change xpath to look for content elements directly

- .github/CODEOWNERS
Switch from Dan and Jacob, who are no longer active on `evalcast`, to @nmdefries, @dshemetov, and @brookslogan.
> Update codeowners for `evalcast`

- R-packages/evalcast/R/evaluate_predictions.R
Currently, truth data is joined on to `predictions_cards` in both `evaluate_covid_predictions`, before calling `evaluate_predictions`, and in `evaluate_predictions`. `evaluate_predictions` is passed separate `actual_data` and doesn't use the truth data contained in `predictions_cards`, so the first join is doing unnecessary work.
- Remove join in `evaluate_covid_predictions` that adds on truth data.
> Drop duplicate truth data join in `evaluate_covid_predictions`

- .github/workflows/python_ci.yml
- .github/workflows/r_evalcast_ci.yml
Github Actions' `ubunu-latest` tag has recently [started referring to Ubuntu 22.04](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/). The R libraries PPA used by `r-lib/actions/setup-r@v1` (deprecated) doesn't support the newest version of Ubuntu, causing the `evalcast` workflow to fail with `E: The repository 'https://ppa.launchpadcontent.net/cran/travis/ubuntu jammy Release' does not have a Release file.` and `Error: Failed to get R 3.5.3: Failed to get R 3.5.3: Failed to install R`. Switch to `r-lib/actions/setup-r@v2` instead, which does support Ubuntu 22.04.
Also use a recent R version.
This stops with a test failure (`Error: Error: 'eval_forecasts' is not an exported object from 'namespace:scoringutils'`), …
> Support Ubuntu 22.04 in CI

- R-packages/evalcast/DESCRIPTION
We no longer need the latest version of `scoringutils`, so move to a slower-moving version. Merge after #614 because it contains a test fix.
> Evalcast: move `scoringutils` source to CRAN from Github

- R-packages/evalcast/DESCRIPTION
- R-packages/evalcast/R/evaluate_predictions.R
- R-packages/evalcast/R/get_predictions.R
- R-packages/evalcast/man/get_predictions.Rd
- R-packages/evalcast/tests/testthat/test-predictions.R
- Fixes #599 
- Also addresses a failing test and a [series of new warnings from dplyr==1.1.0 when using joins](https://github.com/tidyverse/dplyr/releases/tag/v1.1.0)
> Update `get_predictions` to not use `bettermc` when `parallel_execution=FALSE`

- R-packages/modeltools/DESCRIPTION
Modeltools dependencies are out of date and incomplete. Fixing them:
* switch evalcast@main -> evalcast@evalcast
* make quantgen dependency explicit
* make lubridate, MMWRweek, tibble dependencies explicit
> Update `modeltools` dependencies

- R-packages/evalcast/R/get_predictions.R
Not sure why this was set to TRUE, but using parallelism for forecasting is quite tricky due to the many levels where it can be implemented. We've had too many times in production forecasting where eager parallelism settings at a lower level caused memory or other performance issues. Setting the default to FALSE is the safer option. 
Some things to look out for with this change:
- evalcast dashboard possibly becoming single-threaded and slow
- same for forecasting pipeline code
The CI is going to fail due to Python tests getting fixed in #620.
> Evalcast: set get_predictions default to parallel=FALSE

- Python-packages/covidcast-py/DEVELOP.md
- Python-packages/covidcast-py/Makefile
- Python-packages/covidcast-py/covidcast/__init__.py
- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/docs/changelog.rst
- Python-packages/covidcast-py/docs/getting_started.rst
- Python-packages/covidcast-py/docs/index.rst
- Python-packages/covidcast-py/docs/signals.rst
- Python-packages/covidcast-py/setup.py
- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/vignettes/covidcast.Rmd
- R-packages/covidcast/vignettes/multi-signals.Rmd
Preparing changes to be released before rollout of Epidata API Keys.
This PR makes the following changes:
* Python client
* add `use_api_key` as a pass-through to the delphi-epidata python client, which handles keys through a class member
* update package documentation overview warning (this turned into a wall of text, but I'd like to retain the appeal to register if we can -- open to ideas)
* update package documentation getting-started with instructions for applying an API key to requests
* update documentation build process & instructions, which had lost sync
* R client
* add Authorization:Bearer headers using `getOptions`
* update package documentation getting-started with instructions for applying an API key to requests
* update package documentation multi-signals example to not …
> covidcast package updates for API keys

- Python-packages/covidcast-py/covidcast/covidcast.py
- Python-packages/covidcast-py/setup.py
Epidata.auth should be tuple with "epidata" as first element. This change is done in order to make client to send proper request to the backend
> Fix Epidata.auth in covidcast.py

- R-packages/evalcast/DESCRIPTION
- R-packages/evalcast/NEWS.md
- R-packages/evalcast/R/plot_calibration.R
closes #640 
- removes `title` argument from the labs
- also updates the DESCRIPTION file with remotes that work with devtools, remotes, and pak
> bug(evalcast): remove title from labs in plots

- R-packages/covidcast/R/covidcast.R
- R-packages/covidcast/man/covidcast_signals.Rd
I noticed that the documentation for `covidcast_signals()` says 
> The argument structure is just as in `covidcast_signal()`, except the first four arguments `data_source`, `signal`, `start_day`, `end_day` are permitted to be vectors.
However, `covidcast_signal()` has the keyword argument `time_type` and `covidcast_signals()` does not. When using `data_source = "nchs-mortality"`, you need to use `time_type = "week"` or it will error out. Hence, to call `covidcast_signals()` with `data_source = "nchs-mortality"`, we need to tell `covidcast_signal()` to use `time_type = "week"`.
Note: I'm having trouble getting the tests up and running locally, so I'm hoping the CI here will pick up any issues. Is there a suggested way to get the correct package versions?
> Attempt at adding time_type arg

- R-packages/covidcast/vignettes/covidcast.Rmd
- R-packages/covidcast/vignettes/external-data.Rmd
- R-packages/covidcast/vignettes/multi-signals.Rmd
- R-packages/covidcast/vignettes/plotting-signals.Rmd
(maybe) Fixes #633 
Makes the following 1-for-1 swaps:
* all usa-facts--> jhu-csse
* indicator-combination cases and deaths --> jhu-csse
* most case and death signals --> 7dav incident prop
* CTIS cli --> wcli
* doctor-visits cli --> adj cli
With these changes, a single run of `devtools::check(remote = TRUE)` succeeds, but a second run in the same clock hour fails with a rate limit message.
> Switch easy vignette examples to unlimited signals

- R-packages/evalcast/DESCRIPTION
- R-packages/evalcast/NEWS.md
- R-packages/evalcast/R/get_covidhub_predictions.R
- R-packages/evalcast/man/get_covidhub_forecast_dates.Rd
- R-packages/evalcast/man/get_predictions.Rd
Fixes #646.
My R installation is broken, so I can't run the package locally. Hopefully CI can test it here...
> bug: fix get_covidhub_forecast_dates

- R-packages/evalcast/R/get_covidhub_predictions.R
Followup to #647. Because dates are now being fetched using the GitHub API, scripts that request a lot of dates (e.g. forecast eval pipeline) can run into rate limits. When the API is rate-limited, `get_covidhub_forecast_dates` raises a non-informative warning and returns empty dates, causing downstream failures that are hard to debug.
Look for a `GITHUB_PAT` environment variable first, then `GITHUB_TOKEN` if `*_PAT` doesn't exist. If either is found, use it to authenticate the GET requests (using [this header format](https://docs.github.com/en/rest/overview/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication)). Response status codes are checked and if a 403 status is returned, the function exits with an error. It doesn't make sense to warn and return anyway because …
> Try to use GitHub PAT when fetching forecast dates; and check response status for rate limit

- .github/CODEOWNERS
* CI changes will be reviewed by Rostyslav
* Notebooks are no longer in use anywhere, so don't need a dedicated owner
> Update CODEOWNERS for Katie's departure

- R-packages/evalcast/R/get_covidhub_predictions.R
Format differences in forecaster input files means that `value` and `quantile` fields can't all be read as numeric. To avoid errors, read as character and cast to double later. Also specify several `NA`-equivalent values to get `get_forecaster_predictions` working in more cases and to avoid warnings when casting to double in `get_forecaster_predictions_alt`.
The `NA` addition fixes `get_forecaster_predictions` for 8 of the 10 forecasters where read fails for some dates. To fix the remaining failures (for `PSI-DRAFT` and `PSI-DICE` for some dates), apply the same character->double conversion as above.
> Handle cases where `value` and `quantile` columns can't be read as numeric

- R-packages/evalcast/DESCRIPTION
- R-packages/evalcast/NEWS.md
- R-packages/evalcast/R/get_target_response.R
If "cumulative" is in requested signal name, take most recent value per group rather than summing.
Closes https://github.com/cmu-delphi/covidcast/issues/655
> Don't sum cumulative truth values

- R-packages/evalcast/R/get_covidhub_predictions.R
The `forecast-eval` pipeline is running out of memory. Try adding in some `gc()`s to free memory.
Note: There are other places that could be useful to call `gc()`, e.g. during scoring, during truth data fetch, but they would also impact non-forecast eval use. Given that calling `gc()` is a crude fix for OOM issues and that it would be nice for forecast eval to move away from `evalcast` , I don't want to go deep on this change. This is just an easy intervention on a "private" function.
> Call `gc` during `_alt` forecast download function used for forecast eval pipeline

- Python-packages/covidcast-py/covidcast/covidcast.py
> use python package-specific "user agent" string
